### ISSUE TITLE
A slight problem about Different Baseline result

### ISSUE THREAD

**Issue by Ricardokevins** [neulab/BARTScore#13]
Hi, I notice that the QAGSCNN/QAGSXsum ROUGE result in Table5 (Factual Test) is different from other paper (eg. the paper which release this QAGS dataset).
Whether it is because this paper calculates the ROUGE between document and summary while other papers calculate the ROUGE between reference and summary? ( In your experiment setting, you set "ref_sum" same as "src")
I am confused whether baselines for comparison are the same

**Comment by yyy-Apple** [comment]
We calculate the ROUGE between document and summary, while other papers calculate the ROUGE between reference and summary. We do this because factuality describes the relationship between the original text and the generated text.

**Comment by Ricardokevins** [comment]
> We calculate the ROUGE between document and summary, while other papers calculate the ROUGE between reference and summary. We do this because factuality describes the relationship between the original text and the generated text.

OK，thank you for your reply！
