### ISSUE TITLE
How do I map the results in the interval 0 to 1?

### ISSUE THREAD

**Issue by HaoBytes** [neulab/BARTScore#16]
Thank you for sharing the work!

I just want to check how to ensure the result between the 0 and 1? which now results in a negative number.

Thanks

**Comment by yyy-Apple** [comment]
You can take the exponent of the score so that you can get a number between 0 and 1.

**Comment by HaoBytes** [comment]
Thanks!

**Comment by HaoBytes** [comment]
Hello! Thank you for your reply! When I take exponent of the score, the value is only 0.0xxx. is this normal? May I ask what it looks like in itself? Thanks again

**Comment by yyy-Apple** [comment]
This is normal since the vocabulary size is over 50000, and an average probability of 0.0xxx for each word is already high.

**Comment by HaoBytes** [comment]
Thanks!

**Comment by GabrielLin** [comment]
Hi @yyy-Apple Could you please tell me how you calculate the BARTScore in your paper? For example, after using your the code in the repo. I got the BARTScore of the value of -3.111.
`
bs = -3.111
`
`
print(pow(2, bs))
`
`
print(pow(e, bs))
`
Which one do you use? Or you have other methods to get the value between 0-1. Thanks.

**Comment by yyy-Apple** [comment]
Hi, we don't map the scores to the 0 to 1 interval. We just leave them as they are.

**Comment by GabrielLin** [comment]
Hi @yyy-Apple ,  thank you for your fast reply. Do I have the wrong version or do I misunderstanding something? In the paper of the link https://proceedings.neurips.cc/paper/2021/file/e4d2b6e6fdeca3e60e0f1a62fee3d9dd-Paper.pdf , the values of BARTScore in Table 3-6 are values between 0 - 1, but not negative numbers.

**Comment by yyy-Apple** [comment]
Hi, the scores in Table 3-6 are just correlations, not the scores calculated using BARTScore.

**Comment by GabrielLin** [comment]
Thank you @yyy-Apple .

**Comment by GabrielLin** [comment]
Hi @yyy-Apple , I have an additional question. In the Table 5 of this paper https://arxiv.org/abs/2102.00176 , the BARTScore are valeus between 29-43. As we will get a negative number of BS in this repo. Could you please tell me how to get those values in that paper? Thanks.
