### ISSUE TITLE
<mask> token disappear? 

### ISSUE THREAD

**Issue by KpKqwq** [neulab/BARTScore#21]
The bart-base model has a 50265 dictionary but the pretrained model has only 50264? Could you explan it?

**Comment by yyy-Apple** [comment]
(I assume you are referring to the `facebook/bart-large-cnn` model) Because when using `facebook/bart-large-cnn`, the input to our target task does not contain `<mask>` tokens. It makes no difference to add an embedding for the `<mask>` token or not.

**Comment by KpKqwq** [comment]
Thank you for your replay
