### ISSUE TITLE
human scores in QAGS_XSUM are all 0/1

### ISSUE THREAD

**Issue by cyr19** [neulab/BARTScore#25]
Hi,

thanks for your great work.

When I use the extracted dataset of QAGS_XSUM, I found that all fact scores are 0 or 1, which differ from QAGS_CNN. Should it be like that or there is something wrong?

Thanks a lot!

Best,

**Comment by yyy-Apple** [comment]
Hi,

Please refer to the original paper for the QAGS dataset (https://aclanthology.org/2020.acl-main.450.pdf). In particular, the single consistency score is got using the following method. The summary from XSUM is single-sentence, while the summary from CNN contains multiple sentences, which results in different scores.
<img width="518" alt="image" src="https://user-images.githubusercontent.com/50064641/182006660-9ae82d23-92ca-4a95-9cf8-5aaaf8cd28e4.png">

**Comment by cyr19** [comment]
Hi,

I see. thanks a lot for your quick reply.

Best,
