### ISSUE TITLE
Bartscore calculation question

### ISSUE THREAD

**Issue by gmichalo** [neulab/BARTScore#28]
In equation 2 of the paper, Bartscore is calculated as the sum of log probabilities.
However, in line 63 of the bart_score.py is calculated as the average of the log probabilities. 
```
 loss = loss.sum(dim=1) / tgt_len
```

could you let us know which equation is the correct one?

**Comment by yyy-Apple** [comment]
Hi, there is a weighting factor in equation 2, and according to our experiments, we found that the best results can be achieved using a weighting approach where each token is weighted the same (i.e. the weight of each is 1/tgt_len).
