### ISSUE TITLE
Question about unreferenced usage

### ISSUE THREAD

**Issue by susisheng** [neulab/BARTScore#37]
In paper CTRLEval: An Unsupervised Reference-Free Metric for Evaluating Controlled Text Generation, BARTScore is used as a baseline in an unreferenced way but I can't find relative notes about that. Could you pls show how to perform the reference-free evaluation? Thank you very much!

**Comment by yyy-Apple** [comment]
Hi, for using BARTScore in a reference-free way, you just need to use BARTScore to calculate the probability of generating the actual target given the source. For example, like below.
```
bart_scorer.score(['This is the document'], ['This is the summary.'], batch_size=4)
```

**Comment by susisheng** [comment]
Got it! Thank you very much!
