### ISSUE TITLE
A problem while using

### ISSUE THREAD

**Issue by Ricardokevins** [neulab/BARTScore#4]
Awesome Work~~

While using the implement in Repo, I have a question to comfirm:

BARTScore use generate loss as the score to estimate the quality of sentence.
In bart_score.score's implement, I notice the code under:

curr_score_list = [-x.item() for x in loss]

The returned ScoreList contains some negetive value. 
if SummaryA get score -1 while SummaryB get Score -100
Does that means SummaryA  is better than summaryB ?  (becase the loss has been Negated?, loss1 is smaller than loss100)
appreciate any reply ~

**Comment by yyy-Apple** [comment]
Since we are using the average log-likelihood for target tokens, the values should be smaller than 0 (since the probability is between 0 and 1, so the log of it should be negative). 

The higher the log-likelihood, the higher the probability, so the answer to your question is yes.

**Comment by Ricardokevins** [comment]
> Since we are using the average log-likelihood for target tokens, the values should be smaller than 0 (since the probability is between 0 and 1, so the log of it should be negative).
> 
> The higher the log-likelihood, the higher the probability, so the answer to your question is yes.

Thank a lot for your reply  👍  :)

**Comment by neubig** [comment]
@yyy-Apple Could we add this to README.md somewhere? This is not immediately intuitive and I think it probably deserves an explanation.

**Comment by yyy-Apple** [comment]
> @yyy-Apple Could we add this to README.md somewhere? This is not immediately intuitive and I think it probably deserves an explanation.

Have added [`Notes on use`](https://github.com/neulab/BARTScore#notes-on-use) part in README.md
