### ISSUE TITLE
Mutlireference support

### ISSUE THREAD

**Issue by tanay2001** [neulab/BARTScore#5]
Hey there!

I am trying to use the BARTScore metric as follows, but my dataset contains multiple references, is there any feature that I should enable to allow multiple references? I can't seem to find any...

```
from bart_score import BARTScorer
bart_scorer = BARTScorer(device='cuda:0', checkpoint='facebook/bart-large-cnn')
bart_scorer.score(['This is interesting.'], [['This is fun.'],['This is amazing']]) # generation scores from the first list of texts to the second list of texts.
```
Thanks a lot!

**Comment by yyy-Apple** [comment]
Hi, we have added the multi-ref support, please check the `README.md`

**Comment by tanay2001** [comment]
> Hi, we have added the multi-ref support, please check the `README.md`

Thanks a lot
