### ISSUE TITLE
Pearson Correlations results in Table 4

### ISSUE THREAD

**Issue by tanay2001** [neulab/BARTScore#7]
Hi @yyy-Apple 

I had a couple of questions regarding reproducing the scores in Table 4 in the paper, I hope you could help me out

- Are the correlations at the system or sentence level? I went through the experiment setup section and also the SUM folder but couldn't find an answer
- When calculating correlations are the BARTScore values scaled to something like 0-1 range or taken as it is?

Thanks a lot for your time and amazing work!

**Comment by yyy-Apple** [comment]
Hi, thanks for your interest.
1) The correlations are at the summary level.
2) We don't scale BARTScore to 0-1 range. We just keep the score as it is.

**Comment by Atharva-Phatak** [comment]
Hi so in the corrleation score you reported, are those scores negative ? or did the correlation values come positive ?
