### ISSUE TITLE
A question about prompt-based BARTScore

### ISSUE THREAD

**Issue by StevenTang1998** [neulab/BARTScore#8]
Hello, this is a very meaningful work.

I have a question, why is the prompt added to the right of y instead of the left?

For example, if we do a summary task, X is a long document, Y is its summary, and z is the prompt "in summary". I feel "[X]. In summay, [Y]" is more natural than "[X]. [Y], in summary".

Looking forward to your reply, thank you!

**Comment by yyy-Apple** [comment]
Hi~ 
I'm not sure whether there are clarity issues in the paper or the code. If so, feel free to point them out. In our experiments, we only considered the following two cases. 
(1)
Encoder: [X] In summary 
Decoder: [Y]
(2)
Encoder: [X]
Decoder: In summary, [Y]

**Comment by StevenTang1998** [comment]
Thanks for your answering! I understand it!

Sorry I didn’t read it carefully. You explained the details in Section 3.3.1. I read Equation 3 and mistakenly thought that z is behind y.
