### ISSUE TITLE
Multilingual?

### ISSUE THREAD

**Issue by puraminy** [neulab/BARTScore#9]
Can it be used for evaluation of other languages? I tried to used `mbart-50` as checkpoint and changed `bart_score.py` to read this model. 
Also can `mt5` is used with your code? I also tried that and it generates scores in each case. I just wanted to know changing the model and tokenizer is sufficient or not?

**Comment by yyy-Apple** [comment]
To use multilingual BART, you only need to change the model and tokenizer. Below is an example
```python
from transformers import MBartForConditionalGeneration, MBart50Tokenizer
self.tokenizer = MBart50Tokenizer.from_pretrained("facebook/mbart-large-50", src_lang=YOUR_SRC_LANG, tgt_lang=YOUR_TGT_LANG)
self.model = MBartForConditionalGeneration.from_pretrained("facebook/mbart-large-50")
```
